replace_letters = {
    "A" : "Adana",
    "B" : "Bolu",
    "C" : "Ceyhan",
    "D" : "Denizli",
    "E" : "Edirne",
    "F" : "Fatsa",
    "G" : "Giresun",
    "H" : "Hatay",
    "I" : "Isparta",
    "J" : "Jandarma",
    "K" : "Kars",
    "L" : "Lüleburgaz",
    "M" : "Muş",
    "N" : "Niğde",
    "O" : "Ordu",
    "Ö" : "Ödemiş",
    "P" : "Polatlı",
    "R" : "Rize",
    "S" : "Sinop",
    "T" : "Tokat",
    "U" : "Uşak",
    "Ü" : "Ünye",
    "V" : "Van",
    "Y" : "Yozgat",
    "Z" : "Zonguldak",
    "Ç" : "Çanakkale",
    "Ğ" : "Yumuşak G",
    "İ" : "İzmir",
    "Ş" : "Şırnak",
    "Q" : "Q???",
    "X" : "İks",
    "W" : "Çift ve",
    " " : "BOŞLUK",
    "-" : "TIRE",
    "_" : "ALT TIRE",
    "1" : "Bir",
    "0" : "Sifir",
    "2" : "Iki",
    "3" : "UÇ",
    "4" : "dort",
    "5" : "Bes",
    "6" : "Alti",
    "7" : "Yedi",
    "8" : "Sekiz",
    "9" : "Dokuz"
}


lower_upper = {
  "a" : "A",  
  "b" : "B",  
  "c" : "C",  
  "ç" : "D",
  "d" : "E",  
  "e" : "E",  
  "f" : "F",  
  "g" : "G",  
  "ğ" : "Ğ",  
  "h" : "H",  
  "ı" : "I",  
  "i" : "İ",  
  "j" : "J",  
  "k" : "K",  
  "l" : "L",  
  "m" : "M",  
  "n" : "N",  
  "o" : "O",  
  "ö" : "Ö",  
  "p" : "P",  
  "r" : "R",  
  "s" : "S",  
  "ş" : "Ş",  
  "t" : "T",  
  "u" : "U",  
  "ü" : "Ü",  
  "v" : "V",  
  "y" : "Y",  
  "z" : "Z",
  "w" : "W",
  "x" : "X",
  "q" : "Q"
}