name: requirements-check

on:
  push:
  pull_request:
    branches:
      - main



jobs:
  safety:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install --upgrade pip pip-audit
      - name: Check for vulnerabilities
        run: pip-audit --requirement requirements.txt